/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_odps_arrow_TestArrowJni */

#ifndef _Included_com_odps_arrow_TestArrowJni
#define _Included_com_odps_arrow_TestArrowJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_odps_arrow_TestArrowJni
 * Method:    javaToNative
 * Signature: ([B[J[J)V
 */
JNIEXPORT void JNICALL Java_com_odps_arrow_TestArrowJni_javaToNative
  (JNIEnv *, jclass, jbyteArray, jlongArray, jlongArray);

/*
 * Class:     com_odps_arrow_TestArrowJni
 * Method:    nativeToJava
 * Signature: ()Lcom/odps/arrow/DataNode;
 */
JNIEXPORT jobject JNICALL Java_com_odps_arrow_TestArrowJni_nativeToJava
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
